### PR TITLE
ENSWBSITES-320

### PR DESCRIPTION
**Pull request by ens-ds23**
## Type

- [X] Bug fix
- [ ] New feature
- [ ] Improvement to existing feature

## Related JIRA Issue(s)
ENSWBSITES-320

## Importance
Minor

## Description
See ENSWBSITES-320.

Location was being updated twice in nav-panel on focus-object change. 

## Views affected
Genome browser.

### Other effects
None.

- [ ] I have checked any requirements for Google Analytics
- [ ] I have created any required tests
- [X] The PR has as its final commit a WASM/JS update commit if any Rust files were updated.

## Possible complications
Few likely.

### CODE REVIEW

**Comment by azangru** [comment]
image

does this need some additional optimisation?

**Comment by ens-ds23** [comment]
Thanks! I've updated the WASM. I've also updated the build script to do this automatically (so that I don't forget) and will put it in another PR.

**Comment by ens-ds23** [comment]
Do you want to confirm when it's merged @azangru , as you created the original ticket?

**Comment by azangru** [comment]
@ens-ds23 yep, I can confirm that it now looks good on staging (I did check on my local machine before approving, too :smiley: )

**Pull request merged**
