### PR TITLE
[ENSWBSITES-119] Add new stylings to launchbar icons

### PR DESCRIPTION
**Pull request by msmanoj**
Applied new stylings to the launchbar icons and used ImageButton component.

Related JIRA ticket:
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-119

### CODE REVIEW

**Comment by azangru** [comment]
I am a little confused about the semantics of the words "active" and "highlighted". If we press on a button corresponding to a route, and the route gets activated, is the button then "active" or "highlighted"?

**Comment by msmanoj** [comment]
It felt more like you are 'highlighting' the state one button to look different from others.
If you have a look at the storybook entry for [ImageButton](https://ensembl.github.io/ensembl-client/storybook/index.html?path=/story/components-shared-components-imagebutton-trackpanel--bookmarkicon), it seems to be matching with way it is implemented here.

**Comment by imran-ebi** [comment]
Or we can use `selected` instead?

**Comment by azangru** [comment]
I feel that "highlighted" is more about visual presentation while "active" or "selected" are more about the state that a thing is in. I would go with either "active" (which is idiomatic for different react routers) or "selected" here.

**Comment by msmanoj** [comment]
Cool, I've renamed it to 'selected'.

**Pull request merged**
