### PR TITLE
Add sample regulation stats for human and mouse

### PR DESCRIPTION
**Pull request by jyothishnt**
## Type

- [ ] Bug fix
- [ ] New feature
- [x] Improvement to existing feature

## Related JIRA Issue(s)
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-887

## Description
Adds new Regulation section to species stats

## Deployment URL
http://reg-stats.review.ensembl.org/species/homo_sapiens_GCA_000001405_28

## Views affected
Species page

### CODE REVIEW

**Comment by azangru** [comment]
Probably not for this PR, but what I am seeing in the deployment is that we might have expandable sections where the expanded state shows exactly the same data as the collapsed state.

image

I suppose in such a case, we shouldn't be showing the up/down arrow in the right corner of the section. I think I saw @msmanoj discuss it with Andrea, but can't remember for sure. @msmanoj have you added any mechanism for hiding the arrow if there is no extra content in the expanded section, or is it something to be implemented later?

**Review by azangru — APPROVED** [review]
Looks good — but curious to hear about the up/down arrow.

**Comment by msmanoj** [comment]
> Probably not for this PR, but what I am seeing in the deployment is that we might have expandable sections where the expanded state shows exactly the same data as the collapsed state.
> 
> image
> 
> I suppose in such a case, we shouldn't be showing the up/down arrow in the right corner of the section. I think I saw @msmanoj discuss it with Andrea, but can't remember for sure. @msmanoj have you added any mechanism for hiding the arrow if there is no extra content in the expanded section, or is it something to be implemented later?

It is something we need to implement. I might have missed it in the initial PR.

**Review by msmanoj — APPROVED** [review]

**Comment by azangru** [comment]
Created a [Jira ticket](https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-932).

**Pull request merged**
