### PR TITLE
[ENSWBSITES-648] CI/CD job to publish static assets to k8s PVC

### PR DESCRIPTION
**Pull request by kamaldodiya**
## Type

- [ ] Bug fix
- [ ] New feature
- [ ] Improvement to existing feature
- [x] CI/CD

## Related JIRA Issue(s)
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-648

## Description
The CI/CD jobs will publish static assets to the Kubernetes PVC Persistent Volume Claim. Once the build job finishes it passes the job_id (needed to pull the static  assets) to the publish job. The publish CI/CD job will create Kubernetes job, passing project_id, CI/CD job_id,  to pull the static assets from the gitlab and copy it to the PVC. The nginx pod will then serve the static assets from the PVC.

Static-assets

### Concepts & Related Documentation
- Persistent Volume
  -  https://kubernetes.io/docs/concepts/storage/persistent-volumes/
- Passing variables across CI/CD Job
   -  https://docs.gitlab.com/ee/ci/variables/#pass-an-environment-variable-to-another-job
- Kubernetes Job
   - https://kubernetes.io/docs/concepts/workloads/controllers/job/

## Deployment URL

To see it in action visit https://staging-2020.ensembl.org

### Other effects

- [ ] I have checked any requirements for Google Analytics
- [ ] I have created any required tests
- [ ] The PR has as its final commit a WASM/JS update commit if any Rust files were updated.

## Possible complications

-  Need to come up with a strategy to cleanup old assets

### CODE REVIEW

**Review by azangru — APPROVED** [review]
@kamaldodiya As far as I could understand, looks good.

Could you please make sure that the nginx container that serves `/static` path adds the `Service-Worker-Allowed: "/"` header for the `service-worker.js` file that we talked about?

**Comment by kamaldodiya** [comment]
@azangru  It is adding the `Service-Worker-Allowed: "/"` header for the `service-worker.js` it can be seen on staging-2020.enesmbl.org. As such nothing has changed as far as nginx pod and the routes it serves its just instead of getting files from container it gets the files from the PVC.  
Screenshot 2021-07-15 at 14 03 41

**Review by veidenberg — APPROVED** [review]
Looks good to me (as far as I can understand).

**Comment by tuanebi** [comment]
@kamaldodiya You mentioned 3 points under your diagram. Have they already been resolved?

**Comment by kamaldodiya** [comment]
Thank you @tuanebi 
- How to ensure the new assets indeed got copied ?
   - AFAIK there is no way to map the change in source file to the related change in the generated static asset. One thing I could think of is just check the size of the target directory `/usr/data/assets`
- k8s Cron job to cleanup the finished job 
  - This has already been implemented and added as a cron to the master which will do the cleanup for all the successful job nightly. 
- Cleanup policy ? 
  - This about when  and what do we do the cleanup of the static assets itself.
Any of the point here doesn't keep the PR from merging its just that we need to keep this things in mind and have some sort of decision on what to do with it.

**Review by Mehrnaz-Charkhchi — APPROVED** [review]

**Review by tuanebi — APPROVED** [review]

**Pull request merged**
