### PR TITLE
Show only text for External Ref without URL

### PR DESCRIPTION
**Pull request by imransl**
## Type

- [x] Bug fix
- [ ] New feature
- [ ] Improvement to existing feature

## Related JIRA Issue(s)
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-812

## Description
The ExternalLink component always shows the text passed to it as a link, even when there is no URL for it (`to` prop). This PR fixes that by showing the text as a link only if there is a URL for it.

## Views affected
Entity viewer -> sidebar panel

### Other effects
- [ ] I have checked any requirements for Google Analytics
- [x] I have created/modified any required tests
- [ ] The PR has as its final commit a WASM/JS update commit if any Rust files were updated.

### CODE REVIEW

**Comment by azangru** [comment]
But why?

If an external reference does not have a link, then we shouldn't use the ExternalLink component for it. The ExternalLink component should only render links, not non-links.

**Comment by imransl** [comment]
> But why?
> 
> If an external reference does not have a link, then we shouldn't use the ExternalLink component for it. The ExternalLink component should only render links, not non-links.

I was wondering what to do about this. Whether to create a new component called ExternalText or just modify the ExternalLink to make it decide how to display the link. I went ahead with the latter. So do you think we should create that new component then?

**Comment by azangru** [comment]
Can't this be handled by the `ExternalReference` component? So that it calls the `ExternalLink` component if the reference has a link, or renders the text for the reference if there is no link.

**Comment by imransl** [comment]
@azangru We still need ExternalLink's class and icon that are inside it. We can duplicate all that inside ExternalReference, but don't think it'll be a bit messy.

**Comment by azangru** [comment]
> We still need ExternalLink's class and icon that are inside it

Do we? Do we have an example of what an external reference without a link should look like?

**Comment by imransl** [comment]
@azangru I don't think we have. But we don't need to show the icon for an external reference text as Andrea confirmed. So I'll just add it in the `ExternalReference` component as you suggested.

**Comment by azangru** [comment]
Turns out we have a reference design:



As Andrea said, `font-weight: $light` and a left margin of 7px-10px.

**Comment by imransl** [comment]
@azangru I've added the styling in the latest commit: 439279c

**Review by azangru — APPROVED** [review]

**Review by msmanoj — APPROVED** [review]

**Pull request merged**
