### PR TITLE
disable species lozenge on blast small screens

### PR DESCRIPTION
**Pull request by jyothishnt**
## Description
For blast, on small screen, we need to disable all lozenge (when the Add sequence/ Select species buttons appear)

## Related JIRA Issue(s)
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-1685

## Deployment URL(s)
http://disable-species-blast.review.ensembl.org/

## Views affected
Blast

### CODE REVIEW

**Review by azangru — APPROVED** [review]

**Review by imransl — APPROVED** [review]

**Review by msmanoj — APPROVED** [review]

**Comment by ens-ma7** [comment]
sorry to add to this late but the behavior is wrong. According to jira and also to my understanding, the species lozenge should be reenable when moving to the species selection.

image

**Comment by azangru** [comment]
> According to jira and also to my understanding, the species lozenge should be reenable when moving to the species selection.

Oh. I didn't remember that. It makes sense. Shame; the CSS solution was so simple and elegant.

**Comment by azangru** [comment]
@jyothishnt @ens-ma7 I've pushed a commit to address Ridwan's point above.

- Moved back to a JS option
- Disabling the lozenges in a single-column view for the sequence step and enabling them for the species step
- Extracted the breakpoint into a shared js variable that gets reused in two different components, to keep consistency
- Updated/fixed some CSS related to the right page padding

Right padding before:

https://user-images.githubusercontent.com/6834224/192834251-b5f4abb4-ede3-4461-bd68-5737f19a3ec6.mov

Right padding after:

https://user-images.githubusercontent.com/6834224/192834292-6db7ebf1-9485-450b-b77e-91f5b24f4fa9.mov

**Comment by jyothishnt** [comment]
Looks good to me

**Review by ens-ma7 — APPROVED** [review]

**Pull request merged**
