### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by azangru**
## Description
Routine update of project dependencies.

### Notable updates
- typescript updated from 4.7 to 4.8
- jest updated from v. 28 to v. 29 (changed defaults for snapshot formatter, which required updating the snapshots)

## Deployment URL(s)
http://update-dependencies.review.ensembl.org

## Checks
- `npm test` — ✅ 
- `npm run check-types` — ✅ 
- development build — ✅ 
- production build — ✅ 
- `npm run storybook` — ✅

### CODE REVIEW

**Review by ens-ma7 — APPROVED** [review]
Checkout the branch locally, did an npm ci and npm start, all looks good. I also run a few test (npm run test ...) and they worked fine. Also checked the code changes. All good.

**Comment by imransl** [comment]
I encountered two errors when checking this PR locally:

- Lint complaining about `focusable` property of `svg`. This doesn't appear in the `dev` branch though.

Screenshot 2022-09-05 at 12 24 31

- Test cases fail for `blastSequenceAlignmentHelper.test.ts` in this branch as well as `dev`

Screenshot 2022-09-05 at 12 23 51

**Comment by azangru** [comment]
> Test cases fail for blastSequenceAlignmentHelper.test.ts in this branch as well as dev

@imransl update your Node to the latest LTS.

**Comment by imransl** [comment]
> > Test cases fail for blastSequenceAlignmentHelper.test.ts in this branch as well as dev
> 
> @imransl update your Node to the latest LTS.

Tried again after updating Node.js as you suggested and didn't come across those issues.

**Review by imransl — APPROVED** [review]

**Pull request merged**
