### PR TITLE
Fix hidden lozenges

### PR DESCRIPTION
**Pull request by msmanoj**
## Type

- [x] Bug fix
- [ ] New feature
- [ ] Improvement to existing feature

## Related JIRA Issue(s)
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-933

## Description
- Fixed the species lozenges overflow issue on the species page

## Deployment URL
http://hidden-lozenges.review.ensembl.org

## Views affected
http://hidden-lozenges.review.ensembl.org/homo_sapiens_GCA_000001405_28

### Other effects

- [ ] I have checked any requirements for Google Analytics
- [ ] I have created any required tests
- [ ] The PR has as its final commit a WASM/JS update commit if any Rust files were updated.

### CODE REVIEW

**Comment by azangru** [comment]
Doesn't work on Firefox:

image

Although I am fascinated that the height of the container works correctly in Safari, even without the fix.

Here's an idea, because the current CSS grid styles on the root element are wrong. Works on Firefox as well:

image

**Comment by msmanoj** [comment]
> Doesn't work on Firefox:
> 
> image
> 
> Although I am fascinated that the height of the container works correctly in Safari, even without the fix.
> 
> Here's an idea, because the current CSS grid styles on the root element are wrong. Fix them as below, and it will work in Chrome, Safari and FF:
> 
> image

Thanks @azangru. That's done

**Review by imransl — APPROVED** [review]
Works for me

**Review by azangru — APPROVED** [review]
Strangely, the last commit didn't get deployed to the review deployment (you can see there's no green checkmark next to it):

image

but I checked the branch locally, and it works fine in Chrome, Safari and FF.

🚀

**Comment by msmanoj** [comment]
> Strangely, the last commit didn't get deployed to the review deployment (you can see there's no green checkmark next to it):

Not quite sure what happened there. I guess it's something to keep an eye on.

**Pull request merged**
