### PR TITLE
Upgrade webpack to v5

### PR DESCRIPTION
**Pull request by azangru**
## Type
- Housekeeping

## Description
Webpack got updated to version 5, with some breaking changes. This PR is intended to explore ensembl-client's compatibility with webpack 5.

### Notable changes:
- The command for running the dev server has changed (`webpack-dev-server` -> `webpack serve`)
- arguments for webpack-cli have changed; most notably, there is no longer a dot allowed on the `env` parameter (e.g. it's now `--env dev` instead of `--env.mode dev`)
- The most breaking of them all: automatic node polyfills have been removed, and this the `{ node: {fs: false} }` option is no longer working.
- Removed the mechanism for dynamic combinations of webpack configs using presets. This mechanism was based on passing an array of arbitrary strings with the webpack env variable and then using them during config composition. The technique was popularised by Sean Larkin — see his repo that illustrates its use ([package.json](https://github.com/TheLarkInn/webpack-workshop-2018/blob/feature/10-sm-compression-preset/package.json#L9-L10), [entry webpack config file](https://github.com/TheLarkInn/webpack-workshop-2018/blob/feature/10-sm-compression-preset/webpack.config.js#L31), and the [directory with presets](https://github.com/TheLarkInn/webpack-workshop-2018/tree/feature/10-sm-compression-preset/build-utils)). Although this is a beautiful concept, we were not using it for anything; and webpack 5 is no longer allowing arrays of arbitrary strings in the `env` variable.
- Updated storybook. Storybook was the longest blocker, because it packages its own version of webpack, which happens to be webpack 4, and could not, for a while, resolve dependencies conflicts with webpack 5. They are still keeping their own dependency on webpack 4; but at least they have [provided a path to upgrading to webpack 5](https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324) for the end users since version 6.2.

### Other changes:
- Replaced `optimize-css-assets-webpack-plugin` with `css-minimizer-webpack-plugin`, because `css-minimizer-webpack-plugin` is more "official" (being part of the `webpack-contrib` project on github), and the maintainer of `optimize-css-assets-webpack-plugin` seems to be thinking of deprecating his plugin in favour of `css-minimizer-webpack-plugin` (see discussion on `https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/134`)
- Updated webpack workbox plugin to exclude useless files from precaching
- Removed `brotli-webpack-plugin` — it hasn't been updated for webpack 5, and besides, `compression-webpack-plugin`, which we are already using, can compress to brotli just fine
- Removed `robotstxt-webpack-plugin` — it hasn't been updated for webpack 5. Instead, just copying a static robots.txt file from the static directory to the dist directory

## Deployment URL
http://update-webpack.review.ensembl.org

## Tested
- tests and type checking — ✔️ 
- development build — ✔️ 
- production build — ✔️
- service worker — ✔️
- storybook development build – ✔️ 
- storybook production build – ✔️

### CODE REVIEW

**Comment by ens-ma7** [comment]
@azangru one thing i have noticed is that this branch is quite behind from the dev branch, not sure if that makes a difference when testing but when i went to the review URL there was a few things that we fixed that are missing (example the side panel in EV). Do you think it will be good to have the branch updated?

**Comment by imransl** [comment]
Tested everything in my computer. Didn't find anything unusual apart from the huge list of unused variable warnings that got printed in my console (`no-unused-vars`) when I ran `npm run lint`.

**Comment by imransl** [comment]
Just noticed that `npm ci` is failing in the gitlab CI pipeline. I wonder if it is related to what @ens-ma7 mentioned above.

**Comment by azangru** [comment]
> Didn't find anything unusual apart from the huge list of unused variable warnings that got printed in my console (no-unused-vars) when I ran npm run lint.

@imransl thanks! I didn't check the lint. Turns out, there is a well-known problem with the `no-unused-vars eslint` rule and typescript ([see StackOverflow](https://stackoverflow.com/questions/57802057/eslint-configuring-no-unused-vars-for-typescript)). The solution is to use typescript-eslint no-unused-vars rule (see [docs](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md)), which I have now added to eslintrc.

> Just noticed that npm ci is failing in the gitlab CI pipeline. I wonder if it is related to what @ens-ma7 mentioned above.

Kinda 😃 

I added an instruction to the gitlab runner to [update its global `npm` package](https://github.com/Ensembl/ensembl-client/blob/02d682903bbc2b252ed513b64eaaa682397a331f/.gitlab-ci.yml#L27) in this branch, but did not specify the version to which `npm` should be upgraded. So when, following Ridwan's suggestion, I rebased dev and pushed, that triggered a new build. But it just so happened that yesterday, a new `npm` version got released, which found problems in the `package-lock.json` (some integrity 512 sha hash was incorrect). That was why the build was failing. Took me a while to figure that out. So I regenerated the package-lock.json and also fixed the version of the global npm that the gitlab runner is updating to. It fixed the build.

**Comment by imransl** [comment]
@azangru It's great to know everything is fixed now :)

> So I regenerated the package-lock.json and also pinned the version of the global npm that the gitlab runner is updating to. It fixed the build.

So from here onwards are going to pin the `npm` version like this or is this only temporary to fix the CI issue?

**Comment by azangru** [comment]
> So from here onwards are going to pin the npm version like this or is this only temporary to fix the CI issue?

In our CI environment, the npm version has already been defined by the version of node that gets installed. In our case though the LTS version of node (14-something) comes with the previous major version of npm (6-something). I think I had problems initially when I tried to use npm version 6 for the build; but I can try again to check if it is still the case. Just to be sure, I wanted the npm version to be close to what I am using on my dev machine. I would expect you also have npm 7-something if you follow the suggestions of npm cli and upgrade your npm version when it announces that a new version is available.

So to answer your question, you shouldn't need to pin the npm version locally; and we'll probably remove this line from the CI config later on.

**Comment by azangru** [comment]
Yeah, just checked again — npm version 6.14.11 gets stuck while trying to extract the tiny-emitter package (or maybe a package right after it? not sure).

image

It's possible that this is because I have npm 7-something locally, and the package-lock file that it generates poses problems for the npm version 6. I think I'll keep the line upgrading the npm version in the CI config for now 🙂

**Comment by imransl** [comment]
Tested in my local machine once more and the linter has stopped complaining. Didn't find any other issues either.

**Review by imransl — APPROVED** [review]

**Comment by ens-ma7** [comment]
This is the output when i ran npm ci on my checkout (see warning about cwebp):
`ridwan@RIDWAN-W10L:/mnt/c/Users/ridwan/ensembl-client-wsl/ensembl-client/src/ensembl (update-webpack)$ npm ci

Skipping 'fsevents' build as platform linux is not supported
Cached binary found at /home/ridwan/.npm/_cacache/node-sass/5.0.0/linux-x64-64_binding.node
Binary found at /mnt/c/Users/ridwan/ensembl-client-wsl/ensembl-client/src/ensembl/node_modules/node-sass/vendor/linux-x64-64/binding.node
Testing binary
Binary is fine
  ⚠ Command failed: /mnt/c/Users/ridwan/ensembl-client-wsl/ensembl-client/src/ensembl/node_modules/cwebp-bin/vendor/cwebp -version
/mnt/c/Users/ridwan/ensembl-client-wsl/ensembl-client/src/ensembl/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory


  ⚠ cwebp pre-build test failed
  ℹ compiling from source
  ✔ cwebp built successfully
  ✔ pngquant pre-build test passed successfully
  ✔ optipng pre-build test passed successfully
  ✔ mozjpeg pre-build test passed successfully
  ✔ gifsicle pre-build test passed successfully
husky > Setting up git hooks
husky > Done

Skipping 'fsevents' build as platform linux is not supported
added 3405 packages in 368.683s
ridwan@RIDWAN-W10L:/mnt/c/Users/ridwan/ensembl-client-wsl/ensembl-client/src/ensembl (update-webpack)$                                                                                            `

**Comment by imransl** [comment]
@ens-ma7 Seems like you are running this in the Ubuntu Windows Subsystem:

```Skipping 'fsevents' build as platform linux is not supported```.

Does it however work in Windows itself?

**Comment by azangru** [comment]
Skipping fsevents is totally fine; `fsevents` is a MacOS-specific thing:

https://www.npmjs.com/package/fsevents

**Comment by ens-ma7** [comment]
@imransl i have moved away from windows completely in terms of development for 2020. Everything is in WSL (VSCode, npm, node and the 2020 checkout are all in WSL). It is easier this way specially now all the git hooks and lint check works.

**Review by ens-ma7 — APPROVED** [review]

**Pull request merged**
