### PR TITLE
update thoas deprecated byId to by_id

### PR DESCRIPTION
**Pull request by ridwanamo**
## Description
See jira ticket for description of task. Mostly the query files that needs updating to change byId to by_id.

Thoas schema/docs can be seen here:
http://thoas-update.review.ensembl.org/api/thoas (click on the docs button on the right side)

## Related JIRA Issue(s)
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-1775

## Deployment URL(s)
http://thoas-update.review.ensembl.org

## Views affected
Good to check all views to make sure nothing breaks but mostly entity viewer, genome browser (sidebar)

### CODE REVIEW

**Comment by azangru** [comment]
Product is missing.

**Comment by ridwanamo** [comment]
> Product is missing.

I have checked this but couldn't find where we are using byId for product. could you point me to the query or view?

**Comment by azangru** [comment]
https://github.com/Ensembl/ensembl-client/blob/dev/src/content/app/entity-viewer/state/api/queries/proteinDomainsQuery.ts#L24

**Comment by ridwanamo** [comment]
> https://github.com/Ensembl/ensembl-client/blob/dev/src/content/app/entity-viewer/state/api/queries/proteinDomainsQuery.ts#L24

Thanks. Done and push my change

**Review by jyothishnt — APPROVED** [review]

**Review by azangru — APPROVED** [review]

**Pull request merged**
