### PR TITLE
Start SCSS to CSS migration: update webpack rules and migrate shared components

### PR DESCRIPTION
**Pull request by azangru**
## Description
- Updated webpack configs to load CSS files
- Updated Storybook settings
- Migrated SCSS variables to `styles/design-tokens.css`
- Migrated other SCSS partials in the `styles` directory
- Migrated shared components (contents of the `shared` directory), except for the `helpArticle` component

## Related JIRA Issue(s)
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2075

## Deployment URL(s)
http://scss-to-css.review.ensembl.org

### CODE REVIEW

**Comment by jyothishnt** [comment]
Noticed the use of `--color`. Aren't we supposed to use UK spelling `colour`?

**Comment by azangru** [comment]
> Noticed the use of --color. Aren't we supposed to use UK spelling colour?

I was afraid you were going to say that. Personally, I am strongly opposed to this extra letter, because browsers, and CSS in particular, favour American English (`color` without the `u` in the names of CSS rules). Yes, I know we said several years ago that we were going to use British spelling in code; but every time I try, it just feels so awkward and wrong.

**Comment by imransl** [comment]
It's sad that American English has taken over the original English 😞 That aside, do we know of the consensus across Ensembl on which spelling to use?

**Comment by jyothishnt** [comment]
haha not me. I prefer `-color`. But it was Anne who brought this up before, so I just recollected that. Good to respect css rules and also a letter less to type :-) So now we have a consensus between us @imransl  :-)

**Pull request merged**
