### PR TITLE
Update contextual help

### PR DESCRIPTION
**Pull request by azangru**
## Description
- Show contextual help in production environment
- Update the reference to the help article for Species Selector
- Update button styles
  - increase left margin for the conversation icon (after Andrea's request)
  - align both help button and the conversation button to the top (result especially noticeable on the home page)

## Deployment URL
http://update-contextual-help.review.ensembl.org

### CODE REVIEW

**Comment by imransl** [comment]
@azangru The review site is broken so can't test if the help link now works in production

**Comment by azangru** [comment]
@imransl the deployment is up now.

**Review by imransl — APPROVED** [review]

**Comment by jyothishnt** [comment]
Link "species selector app" on the home page help broken? 
Screenshot 2021-08-05 at 13 25 05

**Comment by jyothishnt** [comment]
The modal for contextual help and contact us form  are different in a way that we can click anywhere outside contextual help and close the modal whereas contact us form can only be closed using the close button. Is this how it should be?

**Comment by azangru** [comment]
Both points important, @jyothishnt , but none that we should address in this PR. I've asked what was supposed to happen when the user clicks on the species selector link; it may mean, either opening the species selector app itself or displaying an article about the species selector (if it's the latter, we can't do so yet).

And you are right, we should ask Andrea about the overlay click behaviour.

**Comment by ens-st3** [comment]
@azangru This seems fine for home page, species pages and species selector. Please merge and deploy

**Comment by azangru** [comment]
Updated: Andrea said to remove the link from that contextual help article, which I did.

**Pull request merged**
