### PR TITLE
Use graphql api for EntityViewer topbar

### PR DESCRIPTION
**Pull request by azangru**
## Type
- Refactoring

## Related JIRA Issue(s)
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-493 

## Description
Currently, EntityViewerTopbar is re-using ens-objects fetched from the 2020-genome-search api. Ens-objects will eventually be going away; so this PR switches to using the payload from the toy graphql server.

**Also**
- Removed the `EntityViewerTopbar.test.tsx`. It isn't really testing anything worth testing at this point.

## Views affected
Entity Viewer page

### CODE REVIEW

**Comment by ens-st3** [comment]
Is this also for genome browser navbar ?

**Comment by azangru** [comment]
@ens-st3 nope, just for the Entity Viewer for now. Too many uncertainties about genome browser for now; it is now too much entangled in `ens-object`s. I think we should untangle those when we start migrating from the current 2020-genome-search endpoints to the proper endpoints for getting info about features shown in genome browser.

**Comment by ens-st3** [comment]
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-493 ?

**Comment by azangru** [comment]
@ens-st3 Indeed! The stupid copy-paste :disappointed:

**Pull request merged**
