### PR TITLE
Updated blast config labels

### PR DESCRIPTION
**Pull request by jyothishnt**
## Type

- [ ] Bug fix
- [ ] New feature
- [x] Improvement to existing feature

## Related JIRA Issue(s)
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-1487

## Description
Updated blast labels after review by AndreaW

## Deployment URL
http://update-blast-labels.review.ensembl.org/

## Views affected
Blast

### Other effects
NA
- [ ] I have checked any requirements for Google Analytics
- [ ] I have created any required tests
- [ ] The PR has as its final commit a WASM/JS update commit if any Rust files were updated.

### CODE REVIEW

**Review by azangru — APPROVED** [review]
Labels correspond to the ticket. The label "statistical accuracy" instead of "composition-based statistics" or "composition-based adjustments" makes no sense to me (I've checked the articles referenced in the [docs](https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?pageId=94147939)), but there is nothing I can do. I wish someone like @andrewyatz could review these labels 😞

**Comment by ens-ma7** [comment]
@jyothishnt the review URL isn't working for me. Its giving this error:
`default backend - 404`
can you check if it works for you.

**Comment by ens-ma7** [comment]
> Labels correspond to the ticket. The label "statistical accuracy" instead of "composition-based statistics" or "composition-based adjustments" makes no sense to me (I've checked the articles referenced in the [docs](https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?pageId=94147939)), but there is nothing I can do about it. I wish someone like @andrewyatz could review these labels 😞

I noticed that there is a description field in the json, maybe we can used this with a help icon next to each field. Its just a suggestion, lets see what comes out of the user testing.

**Comment by ens-ma7** [comment]
Probably not related to this PR but i have noticed that HSPs has only one value (100), is that correct? looking at uniprot, the HSPs dropdown has a few options. sorry if it has already been discussed but it feels wrong to have a dropdown with just one value.

**Comment by azangru** [comment]
> Probably not related to this PR but i have noticed that HSPs has only one value (100), is that correct

This is the only (default) value provided by the jDispatcher

> sorry if it has already been discussed but it feels wrong to have a dropdown with just one value

Yes, it is wrong. We'll need to come up with our own list of values; jDispatcher won't give it to us. A similar situation is with the word size, where we are getting three suggested defaults from jDispatcher, but should extend the list with our own values.

**Comment by azangru** [comment]
> I noticed that there is a description field in the json, maybe we can used this with a help icon next to each field.

Yes. But Andrea didn't want question marks next to each field.

**Comment by ens-ma7** [comment]
> > sorry if it has already been discussed but it feels wrong to have a dropdown with just one value
> 
> Yes, it is wrong. We'll need to come up with our own list of values; jDispatcher won't give it to us. A similar situation is with the word size, where we are getting three suggested defaults from jDispatcher, but should extend the list with our own values.

Indeed just noticed there is a jira for this task in the next sprint:
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-1498

**Comment by azangru** [comment]
> @jyothishnt the review URL isn't working for me. Its giving this error:
> default backend - 404
> can you check if it works for you.

The link to the deployment is wrong. Should be `update-blast-labels`, not `updated`. Same as the name of the branch.

**Review by ens-ma7 — APPROVED** [review]

**Pull request merged**
