### PR TITLE
Add licence manager package and precommit hook

### PR DESCRIPTION
**Pull request by azangru**
## Type
🤢 

## Related JIRA Issue(s)
ENSWBSITES-513

## Description
Use the licence manager (extracted in a separate package) in a pre-commit hook to always add licence headers to files that don't have them.

## Views affected
None.

### CODE REVIEW

**Comment by msmanoj** [comment]
I checkedout to this branch and committed a file but it didn't add the licence header. Shouldn't it be adding it?

**Comment by azangru** [comment]
> Shouldn't it be adding it?

It should!
Can you describe your process?
Also, did you run `npm install`?

**Comment by msmanoj** [comment]
> Also, did you run npm install?

Yes, I did.


> Can you describe your process?

I modified a `.tsx` file, staged and committed it.

**Comment by azangru** [comment]
Very strange!

I've just opened `ClearButton.stories.tsx`, replaced `() => {}` with `noop`, saved, committed, and got a licence header during the commit:

image

**Comment by msmanoj** [comment]
Looks like it's something to do with my node version(v10.15.2):
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

I've updated it and it works now.

**Comment by msmanoj** [comment]
Sorry! closed by mistake.

**Pull request merged**
