### PR TITLE
Remove entity type indicator

### PR DESCRIPTION
**Pull request by jyothishnt**
## Type

- [ ] Bug fix
- [ ] New feature
- [x] Improvement to existing feature

## Related JIRA Issue(s)
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-779

## Description
Entity type indicator is no more needed

## Deployed URL
http://remove-entitytypeindicator.review.ensembl.org/entity-viewer/homo_sapiens_GCA_000001405_28/gene:ENSG00000139618?view=transcripts

## Views affected
Entity Viewer

- [] I have checked any requirements for Google Analytics
- [ ] I have created any required tests
- [ ] The PR has as its final commit a WASM/JS update commit if any Rust files were updated.

### CODE REVIEW

**Comment by ens-ma7** [comment]
can i have the deploy URL please? just want to make sure spacing on the top bar looks fine. thanks

**Review by azangru — APPROVED** [review]

**Comment by jyothishnt** [comment]
URL added to description @ens-ma7

**Comment by ens-ma7** [comment]
Thanks for the URL @jyothishnt All looks good. Just one thing to note though is that from the new species homepage design (https://xd.adobe.com/view/27d0b9b2-60e4-4f25-8af4-9edd440fe2f5-7283/screen/db166cfe-50e4-4fb1-9169-123f3a0d66ad?fullscreen) there is "Data for this species" text in this place.  Just something to keep in mind if we need adding later.

**Review by ens-ma7 — APPROVED** [review]

**Comment by jyothishnt** [comment]
> Thanks for the URL @jyothishnt All looks good. Just one thing to note though is that from the new species homepage design (https://xd.adobe.com/view/27d0b9b2-60e4-4f25-8af4-9edd440fe2f5-7283/screen/db166cfe-50e4-4fb1-9169-123f3a0d66ad?fullscreen) there is "Data for this species" text in this place. Just something to keep in mind if we need adding later.

Yes. But this is just a text and not a round button.

**Pull request merged**
