### PR TITLE
Feature/use animation library

### PR DESCRIPTION
**Pull request by ens-ds23**
## Type

- [ ] Bug fix
- [ ] New feature
- [X] Improvement to existing feature

## Related JIRA Issue(s)
None

## Importance
Needs to go in to allow animation fixes hanging off the back of it, but not super time-critical.

## Description
This is a rewrite of the animations in the genome browser to use an separate library. That library has a proper API, good unit tests, and compiles (and is testable) independently of and in parralel with the main code. The new API will mean that custom animations are easier to write. It also handles corner cases correctly such as chained animations, animations abandoned due to contrary user action, etc.

There are no performance tweaks here (this code doesn't relate to that).

## Views affected
Genome Browser

### Other effects
None

- [ ] I have checked any requirements for Google Analytics
- [ ] I have created any required tests
- [X] The PR has as its final commit a WASM/JS update commit if any Rust files were updated.

## Possible complications
None anticipated.

### CODE REVIEW

**Comment by ens-ds23** [comment]
JIRA is ENSWBSITES-369

**Comment by ens-ds23** [comment]
Added merge commit of WASM blob name due to conflict from previous PR.

**Comment by ens-ds23** [comment]
Added merge commit of WASM blob name due to conflict from previous PR.

**Comment by imran-ebi** [comment]
Can we merge this PR to dev?

**Pull request merged**
