### PR TITLE
ENSWBSITES-959: remove sequence section in EV Right Hand panel

### PR DESCRIPTION
**Pull request by ens-ma7**
## Type

- [ ] Bug fix
- [ ] New feature
- [x] Improvement to existing feature

## Related JIRA Issue(s)
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-959

## Importance
N/A

## Description
Removing the sequence section in the Entity viewer Right Hand panel. Not sure if there is anything else that needs removing.

## Deployment URL
http://no-sequence-section.review.ensembl.org

## Views affected
Entity viewer Right Hand Panel

### Other effects
None

- [ ] I have checked any requirements for Google Analytics
- [ ] I have created any required tests
- [ ] The PR has as its final commit a WASM/JS update commit if any Rust files were updated.

## Possible complications
None

### CODE REVIEW

**Comment by msmanoj** [comment]
Hi @ens-ma7 - can you please also remove `sequence` from the following line:
https://github.com/Ensembl/ensembl-client/pull/467/files#diff-d11b258c8a252346e4c9f7a03ece1291233e956a4fe6746df34923e31b75812bL37

**Comment by azangru** [comment]
Do you mean this line? https://github.com/Ensembl/ensembl-client/blob/154f560dd59170cff2724da8a139c181f5e69d6d/src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/MainAccordion.tsx#L37 The link didn't work...

**Comment by ens-ma7** [comment]
@msmanoj i also couldn't get the link you send to work, can you send again or is it the one that @azangru mention.

**Comment by msmanoj** [comment]
> @msmanoj i also couldn't get the link you send to work, can you send again or is it the one that @azangru mention.
Sorry @ens-ma7. It's the one Andrey shared

**Comment by ens-ma7** [comment]
Thats done @msmanoj can you review/approve please.

Thanks

**Review by azangru — APPROVED** [review]
looks good

**Review by msmanoj — APPROVED** [review]

**Pull request merged**
