### PR TITLE
Remove duplicate import from useEntityViewerAnalytics

### PR DESCRIPTION
**Pull request by msmanoj**
## Description
- Remove duplicate import from `useEntityViewerAnalytics.ts`

### CODE REVIEW

**Comment by azangru** [comment]
While you are at it, can you annotate type imports (that are type aliases rather than enums). I can see at least RootState that could benefit from `import type`

**Comment by msmanoj** [comment]
> While you are at it, can you annotate type imports (that are type aliases rather than enums)? I can see at least RootState that could benefit from `import type`. `AnalyticsOptions`, `Filters`, `SortingRule` seem to be type aliases as well.

That's done

**Comment by azangru** [comment]
Aren't both of these type aliases?

image

If yes, then it's `import type {Filters, SortingRule}`

**Review by azangru — APPROVED** [review]
I just pushed a commit for my latest comment.

**Comment by msmanoj** [comment]
Sorry, I missed to get back early. `SortingRule` is an enum.

**Comment by azangru** [comment]
> `SortingRule` is an enum.

It's not used as a value here though. Not as `SortingRule.SOMETHING`.

Typescript was quite happy with the build after my latest commit.

**Pull request merged**
